#version: 1.0.(build)

platform:
  - x64

image:
  - Visual Studio 2015
  - Visual Studio 2017

skip_branch_with_pr: true

build:
  verbosity: detailed

clone_folder: c:\projects\causal-sets-explorer

shallow_clone: true

configuration: Release

install:
  # Upgrade pip
  - python -m pip install --upgrade pip
  # Install Conan
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%\Scripts\
  - pip.exe install conan

before_build:
  - cd C:\projects\causal-sets-explorer
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - mkdir build
  - cd build
  - conan profile new default --detect
  - conan install .. -pr default --build=missing
  - conan build ..

on_success:
#  - ctest
#  - cd bin
#  - causal_sets_explorer.exe

test_script:
#  - cd bin
#  - pwd
#  - causal_sets_explorer_test.exe
#  - cmake --build .. --target test
  - ctest -C Release

notifications:
  - provider: Email
    to:
      - acgetchell@ucdavis.edu
    on_build_status_changed: true

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
