#version: 1.0.(build)

platform:
  - x64

image:
  - Visual Studio 2015

skip_branch_with_pr: true

build:
  verbosity: detailed

clone_folder: c:\projects\causal-sets-explorer

shallow_clone: true

configuration: Release

#cache:
#  - C:\.conan
#  - C:\Users\appveyor\.conan -> registry.txt

install:
  # Install Conan
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%\Scripts\
  - pip.exe install conan
  - conan user # create the conan data directory
  - conan --version
  # Verify CMake
  - cmake --version

before_build:
  - cd C:\projects\causal-sets-explorer
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - mkdir build
  - cd build
  - conan install .. --build=missing
#  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release ..
#  - cmake --build .
  - conan build ..

on_success:
  - cd bin
  - causal_sets_explorer.exe
#  - cd
#  - cmake --build .. --target test

#test_script:
##  - unittests.exe
#  - cd bin
#  - cmake --build .. --target test

notifications:
  - provider: Email
    to:
      - acgetchell@ucdavis.edu
    on_build_status_changed: true

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
