codecov:
  token: f5c9c4b4-233b-432e-a0ba-3790b49a2046
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "30...100"

  status:
    project:
      default:
        threshold: 3%
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false