language: cpp
sudo: false

addons:
  apt:
    packages:
      - g++-6
      - ninja-build
    sources: &sources
      - ubuntu-toolchain-r-test

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      language: generic
#      env: COMPILER=apple-clang VERSION=8.0 LIB=libc++

    # gcc
    - os: linux
      dist: trusty
#      env: COMPILER=gcc VERSION=6.3 LIB=libstdc++

before_install:
# Workaround for https://github.com/travis-ci/travis-ci/issues/6307
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
      rvm get stable --auto-dotfiles
      brew update
    fi

install:
#  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew unlink cmake
      brew upgrade cmake
      brew install ninja
      brew install conan
    else
      pip install conan
    fi
  - cmake --version
  - if [[ "$CXX" = "g++" ]]; then export CXX="g++-6" CC="gcc-6"; fi

script:
  - mkdir build && cd build
  - conan install .. --build=missing
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .

after_script:
  - (cd bin && ./causal_sets_explorer)
  - (cd bin && ./unittests)