language: cpp
sudo: false
dist: trusty
osx_image: xcode8.2

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ToO9QZzFgcpkrDaOOmtT35KueD1ijh0slAhgSoHxHI5uZuuZYkM3N/1pMZYbFdXtvjIRdqquDYBsvWiofo75dXZ4TTGdfwew43R5r4mB4kmzzgCc4rG8TD85Q8fx8L1x9OLMpNPAFwl1tfxP6dRFTcte2SdOJ2fQUONNNP5wRPy1Fa4zvquUWipj1UK8IJV0CpV4Rke5AXF+g+W1d0Cit03r9J0wY5Men+YZvt0BAbghtvwXtmcDAD8bNt4EzTPLGLMmk1SjkCW5434EZXIb8cIGCnA1gxR1VN2bwQ37SsumVfRh+dfbaxETFQYrHaLTi0VBOqYJyEBvXYgMyTklP3J2UTbm8/Hcs/rWkVTohLzmkmOCBktROe0haeh9Tb1lRjTeqGxjmW4CRNSRS8VdSICQXBiDf+IxVL6242fOYFMAn3Z1Vv/wP6ujVD63WCyeLnOOxZG81tgmIo0XsDssIToJkQKZUf4rRhNMkLgdJxNA6xWO85qYRb3PIGHAToSnYRNsbFQd2Dk/UnBdrG5B9mWGI6fBSrUl9GI2p07E8F/UrJC5xkMWgL14fIUEPcMip+u+Sn80eFW2FvAIqheYf3w7K/q7w23oJT53KpDBakxzFMZfcp0KdH+QIUECg/ULWGjsnaSnZgvTJm4O5Lt/Hb4kisAJHfQP856Ddy6/owI="

addons:
  apt:
    packages:
      - g++-6
      - ninja-build
      - clang-3.9
      - lldb-3.9
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.9
  coverity_scan:
      project:
        name: "acgetchell/causal-sets-explorer"
        description: "Build submitted via Travis CI"
      notification_email: acgetchell@ucdavis.edu
      build_command_prepend: "mkdir build && cd build && conan install .. --build=missing"
      build_command:   "cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .."
      branch_pattern: coverity-scan

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: gcc

before_install:
# Workaround for https://github.com/travis-ci/travis-ci/issues/6307
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
      rvm get stable --auto-dotfiles
      brew update
    fi
# Coverity
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-


install:
#  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew unlink cmake
      brew upgrade cmake
      brew install gcc
      brew link --overwrite gcc
      brew install ninja
      brew install conan
    else
      CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
      pip install conan
    fi
  - cmake --version
  - if [[ "$CXX" = "g++" ]]; then export CXX="g++-6" CC="gcc-6"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "clang++" ]]; then export CXX="clang++-3.9" CC="clang-3.9"; fi

script:
  - |
    if [[ "${COVERITY_SCAN_BRANCH}" != 1 ]]; then
      mkdir build && cd build
      conan install .. --build=missing
      cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
      cmake --build .

after_success:
  - (cd bin && ./causal_sets_explorer)
  - (cd bin && ./unittests)