language: cpp

os: osx

osx_image: xcode8.2

before_install:
  - brew update

install:
  - brew unlink cmake
  - brew upgrade cmake
  - brew install conan
  - brew install ninja
  - cmake --version

script:
  - mkdir build && cd build
  - conan install .. -s compiler=apple-clang -s compiler.version=8.0 -s compiler.libcxx=libc++ --build=missing
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release
  - cmake --build .

after_script:
  - (cd build/bin && ./causal_sets_explorer)