os: linux
services:
   - docker
sudo: required
language: python
env:
  matrix:
    - DOCKER_IMAGE=lasote/conangcc63 # 6.3
    - DOCKER_IMAGE=lasote/conanclang39 # 3.9

matrix:
   include:
       - os: osx
         osx_image: xcode8.2 # apple-clang 8.0
         language: generic
         env:

before_install:
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
