language: cpp
sudo: false
dist: trusty
osx_image: xcode8.2

addons:
  apt:
    packages:
      - g++-6
      - ninja-build
      - clang-4.0
      - lldb-4.0
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: gcc

before_install:
# Workaround for https://github.com/travis-ci/travis-ci/issues/6307
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
      rvm get stable --auto-dotfiles
      brew update
    fi

install:
#  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew outdated cmake || brew upgrade cmake
      brew install gcc
      brew link --overwrite gcc
      brew install ninja
      brew install conan
    else
      CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
      pip install conan
    fi
  - cmake --version
  - if [[ "$CXX" = "g++" ]]; then export CXX="g++-6" CC="gcc-6"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "clang++" ]]; then export CXX="clang++-4.0" CC="clang-4.0"; fi

script:
  - mkdir build && cd build
  - conan install .. --build=missing
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DGMOCK_TESTS:BOOL=ON ..
  - cmake --build .
#  - conan build ..

after_success:
  - (cd bin && ./causal_sets_explorer)
  - (cd bin && ./unittests)