language: cpp
sudo: false
dist: xenial
#osx_image: xcode9.4

addons:
  apt:
    packages:
      - g++-6
      - ninja-build
      - clang-6.0
      - valgrind
      - python3-pip
      - python3-setuptools
    sources:
#      - ubuntu-toolchain-r-test
#      - llvm-toolchain-trusty-6.0

#cache:
#  - pip
#  - ccache
#  - directories:
#    - /home/travis/.conan/data/

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  fast_finish: true
#  include:
#    - os: linux
#    - compiler: gcc
#    - env: VALGRIND=true
  allow_failures:
    - os: osx
      compiler: gcc

before_install:
# Fix "fatal error: _stdio.h: No such file or directory"
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      sudo softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode 9.4.1"
    fi
#  - pip install --upgrade pip

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install ccache
      export PATH="/usr/local/opt/ccache/libexec:$PATH"
      brew install gcc
      brew link --overwrite gcc
      brew install ninja
      brew install conan
    else
      sudo pip3 install conan
    fi
  - if [[ "$CXX" == "g++" ]]; then export CXX="g++-6" CC="gcc-6"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "clang++" ]]; then export CXX="clang++-6.0" CC="clang-6.0"; fi
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

script:
  - mkdir build && cd build
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ "$CXX" == "g++" ]]; then
        echo osx/g++
        conan install .. --build=missing -s os=Macos -s compiler=gcc -s compiler.version=6
      else
        echo osx/clang auto-detection works
        conan install .. --build=missing
      fi
    else
      if [[ "$CXX" == "g++" ]]; then
        echo linux/g++
        conan install .. --build=missing -s os=Linux -s compiler=gcc -s compiler.version=6 compiler.libcxx=libstdc++11
      else
        echo linux/clang auto-detection works
        conan install .. --build=missing
      fi
    fi
  - conan build ..

after_success:
  - cmake --version
  - cd bin
  - ./causal_sets_explorer
  - if [[ ${VALGRIND} == "true" ]]; then valgrind --leak-check=full --show-leak-kinds=all ./causal_sets_explorer
  # CTest
  - cmake --build .. --target test

notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com

    on_success: never
    on_failure: always
