language: cpp
sudo: false
dist: trusty
osx_image: xcode9.4

addons:
  apt:
    packages:
      - g++-8
      - ninja-build
      - clang-6.0
      - valgrind
      - python3-pip
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0

#cache:
#  directories:
#    - ${HOME}/.conan/data

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  fast_finish: true
#  include:
#    - os: linux
#    - compiler: gcc
#    - env: VALGRIND=true
#  allow_failures:
#    - os: linux
#      compiler: clang

before_install:
# Workaround for https://github.com/travis-ci/travis-ci/issues/6307
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
      rvm get stable --auto-dotfiles
      brew update
    fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install gcc
      brew link --overwrite gcc
      brew install ninja
      brew install conan
    else
      sudo pip3 install conan
    fi
  - if [[ "$CXX" == "g++" ]]; then export CXX="g++-8" CC="gcc-8"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "clang++" ]]; then export CXX="clang++-6.0" CC="clang-6.0"; fi
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

script:
  - mkdir build && cd build
  - |
    if [[ "$CXX" == "g++" ]]; then
      conan install .. --build=missing -s compiler=gcc -s compiler.version=8 -s compiler.libcxx=libstdc++11
    else
      conan install .. --build=missing
    fi
#  - conan install .. --build=missing
#  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DGMOCK_TESTS:BOOL=ON ..
#  - cmake --build .
  - conan build ..

after_success:
  - cmake --version
  - cd bin
  - ./causal_sets_explorer
  - ./causal_sets_explorer_test
  - if [[ ${VALGRIND} == "true" ]]; then valgrind --leak-check=full --show-leak-kinds=all ./causal_sets_explorer
  # CTest
  - cmake --build .. --target test

notifications:
  webhooks: https://www.travisbuddy.com
  on_success: never
