name: Linux Clang

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13
          platform: x64

      - name: Setup
        run: |
          sudo apt update
          sudo apt-get install ninja-build ccache

      - uses: eic/setup-cvmfs@main
      - uses: eic/setup-spack@main

      - name: Install spack packages and configure CMake
        shell: bash
        run: |
          spack install boost
          spack install catch2
          spack load boost
          spack load catch2
          cmake -G Ninja -D CMAKE_BUILD_TYPE=Release -D ENABLE_TESTING:BOOL=TRUE -S . -B build

      - name: Build
        run: cmake --build build